# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{git-pivotal}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ignacio Ortega"]
  s.date = %q{2011-01-11}
  s.description = %q{A collection of git utilities to ease integration with Pivotal Tracker}
  s.email = %q{ignacio.ortega@gmail.com}
  s.executables = ["git-finish", "git-pick", "git-chore", "git-bug", "git-feature"]
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "Rakefile",
    "VERSION",
    "bin/git-bug",
    "bin/git-chore",
    "bin/git-feature",
    "bin/git-finish",
    "bin/git-pick",
    "git-pivotal.gemspec",
    "lib/commands/base.rb",
    "lib/commands/bug.rb",
    "lib/commands/chore.rb",
    "lib/commands/feature.rb",
    "lib/commands/finish.rb",
    "lib/commands/pick.rb",
    "lib/git-pivotal.rb",
    "readme.markdown",
    "spec/commands/base_spec.rb",
    "spec/commands/bug_spec.rb",
    "spec/commands/chore_spec.rb",
    "spec/commands/feature_spec.rb",
    "spec/commands/finish_spec.rb",
    "spec/factories.rb",
    "spec/factory.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/iortega/git-pivotal}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A collection of git utilities to ease integration with Pivotal Tracker}
  s.test_files = [
    "spec/commands/base_spec.rb",
    "spec/commands/bug_spec.rb",
    "spec/commands/chore_spec.rb",
    "spec/commands/feature_spec.rb",
    "spec/commands/finish_spec.rb",
    "spec/factories.rb",
    "spec/factory.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<pivotal-tracker>, ["~> 0.3.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<pivotal-tracker>, ["~> 0.3.1"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<pivotal-tracker>, ["~> 0.3.1"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

